Add CheckDestroy step for Packer Data Source Test (#180)
* Add CheckDestroy step for Packer Data Source Test

This change adds a few new helper functions for deleting resources on
the HCP Packer registry under tests.

Test Results After Change
```
make testacc TESTARGS='-count=1 -run=TestAcc_dataSourcePacker'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/... -v -count=1
-run=TestAcc_dataSourcePacker -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients
[no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul
0.172s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input
0.127s [no tests to run]
=== RUN   TestAcc_dataSourcePacker
--- PASS: TestAcc_dataSourcePacker (6.47s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider
6.815s
```

* Fix panic when requesting a channel that has no assigned iteration

After change
```
    data_source_packer_image_iteration_test.go:284: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: no iteration information found for the specified channel production

          with data.hcp_packer_image_iteration.alpine,
          on terraform_plugin_test.tf line 4, in data "hcp_packer_image_iteration" "alpine":
           4:   data "hcp_packer_image_iteration" "alpine" {

--- FAIL: TestAcc_dataSourcePacker (2.68s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-hcp/internal/provider   3.246s
FAIL
make: *** [testacc] Error 1
```

* Update error handling for resource creation

This change adds a new updateChannel function to handle the updating of
a test channel that may have been created in a previous run, but not
cleaned up.