Data source for packer registry (#169)
* add file for packer registry

* add packe registry to provider.go

* packer client


* flattenPackerBuildList

* fix pointer type errors after dependency update

more ptr stuff

* Update data_source_packer_image.go

* add & run tests

* Update data_source_packer_image.go

* it works !

* go mod tidy

* fix description for bucket

remove `ID` reference, as this is a slug

* nest iteration stuff under iteration

* start showing builds & hcp_packer_image -> hcp_packer_image_iteration

* Revert "fix pointer type errors after dependency update"

This reverts commit 7500dacfc78747d3f065a467093e8482bc4aed1f.

* Update internal/provider/data_source_packer_image_iteration.go

Co-authored-by: Brenna Hewer-Darroch <21015366+bcmdarroch@users.noreply.github.com>

* Update internal/provider/data_source_packer_image_iteration.go

* up go mods

* Update data_source_packer_image_iteration.go

* Create packer_image_iteration.md

* make channel mandatory for now

* go get github.com/hashicorp/hcp-sdk-go@v0.11.0 && go mod tidy

* Update internal/provider/data_source_packer_image_iteration.go

Co-authored-by: Brenna Hewer-Darroch <21015366+bcmdarroch@users.noreply.github.com>

* Create data-source.tf

* Create packer_image_iteration.md.tmpl

* Update packer_image_iteration.md

* Delete data_source_packer_image_iteration_test.go

* Update data_source_packer_image_iteration.go

remote "id" part as it's already in there

* Update packer_image_iteration.md

* Revert "Delete data_source_packer_image_iteration_test.go"

This reverts commit 5512bacdd141a897a854ca624fa4b0664de56528.

* auto-upsert acc tests data

* go get github.com/hashicorp/hcp-sdk-go@v0.12.0 && tidy

* Update data_source_packer_image_iteration.go

* Update data_source_packer_image_iteration_test.go

* go get -u github.com/hashicorp/terraform-json

to fix a weird 'Step 1/1 error: unsupported state format version: expected "0.1", got "0.2"' error

* manually fix docs

* Add CheckDestroy step for Packer Data Source Test (#180)

* Add CheckDestroy step for Packer Data Source Test

This change adds a few new helper functions for deleting resources on
the HCP Packer registry under tests.

Test Results After Change
```
make testacc TESTARGS='-count=1 -run=TestAcc_dataSourcePacker'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/... -v -count=1
-run=TestAcc_dataSourcePacker -timeout 120m
?       github.com/hashicorp/terraform-provider-hcp/internal/clients
[no test files]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/consul
0.172s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/input
0.127s [no tests to run]
=== RUN   TestAcc_dataSourcePacker
--- PASS: TestAcc_dataSourcePacker (6.47s)
PASS
ok      github.com/hashicorp/terraform-provider-hcp/internal/provider
6.815s
```

* Fix panic when requesting a channel that has no assigned iteration

After change
```
    data_source_packer_image_iteration_test.go:284: Step 1/1 error: Error running pre-apply refresh: exit status 1

        Error: no iteration information found for the specified channel production

          with data.hcp_packer_image_iteration.alpine,
          on terraform_plugin_test.tf line 4, in data "hcp_packer_image_iteration" "alpine":
           4:   data "hcp_packer_image_iteration" "alpine" {

--- FAIL: TestAcc_dataSourcePacker (2.68s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-hcp/internal/provider   3.246s
FAIL
make: *** [testacc] Error 1
```

* Update error handling for resource creation

This change adds a new updateChannel function to handle the updating of
a test channel that may have been created in a previous run, but not
cleaned up.

Co-authored-by: Megan Marsh <megan@hashicorp.com>
Co-authored-by: Brenna Hewer-Darroch <21015366+bcmdarroch@users.noreply.github.com>
Co-authored-by: Wilken Rivera <wilken@hashicorp.com>